// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Yesen_MultiCycleValue","status":true,"description":"","parameters":{}},
{"name":"Yesen_SkipTitle","status":true,"description":"","parameters":{}},
{"name":"Yesen_WindowsChange","status":true,"description":"","parameters":{}},
{"name":"PicturecallCommon","status":true,"description":"Clickable picture plugin","parameters":{"TransparentConsideration":"OFF","GameVariablePictureNum":"0"}},
{"name":"2w_message","status":true,"description":"显示文本加强","parameters":{}},
{"name":"2w_moremessage","status":true,"description":"���봰���л�","parameters":{}},
{"name":"saveOnPathwww","status":true,"description":"保存时如果是打包pc端www文件夹的时候,放到与www同级文件夹里","parameters":{}},
{"name":"2w_peiyin","status":true,"description":"","parameters":{}}
];
